# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# paul's
GOOGLE_API_CLIENT_ID: 1013188951705-vtisha5kei3mn2bbstdsjkpuehp7q43k.apps.googleusercontent.com
GOOGLE_API_CLIENT_SECRET: PYpjH76UEFoT669aYRKnCZZn

# paul's
GITHUB_CLIENT_ID: 0b5bd2977107acc02a01
GITHUB_CLIENT_SECRET: 64dfdf87f4603802a9c305596d3c285417af955b

# pauls
OUTLOOK_APPLICATION_ID: 6053b81b-9547-4121-a335-8dca09feae55
OUTLOOK_PASSWORD: Hcwkz1umLNyPVQiASXuHKjW


# Thando's
TWITTER_CONSUMER_KEY: X9xDEwyMeb5rCWU6IYS3mMteX
TWITTER_CONSUMER_SECRET: SiU9mjmAIQYeKwVTbqW7KfSeX6Uml8YXI3FVSpdVT7NCXybfzH
